# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\".\n\x11ListUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User2\xab\x01\n\x0bUserService\x12\x31\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\n.user.User\x12+\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\n.user.User\x12<\n\tListUsers\x12\x16.google.protobuf.Empty\x1a\x17.user.ListUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=55
  _globals['_USER']._serialized_end=102
  _globals['_CREATEUSERREQUEST']._serialized_start=104
  _globals['_CREATEUSERREQUEST']._serialized_end=152
  _globals['_GETUSERREQUEST']._serialized_start=154
  _globals['_GETUSERREQUEST']._serialized_end=182
  _globals['_LISTUSERSRESPONSE']._serialized_start=184
  _globals['_LISTUSERSRESPONSE']._serialized_end=230
  _globals['_USERSERVICE']._serialized_start=233
  _globals['_USERSERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
